### ISSUE TITLE
Add RANDOM Support(RAS) and better error message reporting for Parser(BEMP)

### ISSUE THREAD

**Issue by TENTHER101** [TENTHER101/TEPL#10]
ARS
====
- Currently: 
```
set x to random num from 0 to 100 
Syntax error in input!
Traceback (most recent call last):
  File "/home/runner/TEPL-V-07375/./src/main.py", line 67, in <module>
    main()
  File "/home/runner/TEPL-V-07375/./src/main.py", line 63, in main
    interpret(result)
  File "/home/runner/TEPL-V-07375/src/interpreter.py", line 45, in interpret
    if ast[0] == 'OUTPUT':
TypeError: 'NoneType' object is not subscriptable 
```
- Returns an error message. 
<br>

- TODO: 
```
set x to random num from 0 to 100
output x
```
- Returns a random integer/number from 0 to 100. 

<br>

BEMP 
====
- Currently: 
```
set x too 5
Syntax error in input!
Traceback (most recent call last):
  File "/home/runner/TEPL-V-07375/./src/main.py", line 67, in <module>
    main()
  File "/home/runner/TEPL-V-07375/./src/main.py", line 63, in main
    interpret(result)
  File "/home/runner/TEPL-V-07375/src/interpreter.py", line 45, in interpret
    if ast[0] == 'OUTPUT':
TypeError: 'NoneType' object is not subscriptable
```
- Returns an explicit error message and continues to the interpreter even when an error has already been found. 

<br>

- TODO: 
```
set x too 5
Syntax error at 'too', expected 'to'!
```
- Returns a helpful error message and does not continue to the interpreter.

**Comment by TENTHER101** [comment]
RAS completed. BEMP remains as TODO.

**Comment by TENTHER101** [comment]
Not entirely completed however it is well completed enough for V1.35.00, V1.80.00 bug reporting is yet to be added.
